
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-subscription
  namespace: dapr-apps
spec:
  topic: orders
  routes:
    rules:
    - match: "true"
      path: /orders
  pubsubname: snssqs-pubsub
scopes:
- orderservice
